#!/bin/sh

if [ ! -x ./cl ]
then
	echo Compile ./cl first
	exit 1
fi

for TNAME in tests.in/test.???
do
	OUTPUT=`basename $TNAME`
	echo "Running test $OUTPUT"
	./cl -p < $TNAME > tests.output/$OUTPUT
	DESIRED=tests.out/$OUTPUT
	if [ -r $DESIRED ]
	then
		if diff $DESIRED tests.output/$OUTPUT > /dev/null
		then
			:
		else
			echo "Test $OUTPUT failed"
		fi
	else
		echo "No desired output specified for $OUTPUT"
	fi
done
